on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Get Branch Name
      run: |
        branchname=$(git rev-parse --abbrev-ref HEAD)
        echo "branchname=$branchname" >> "$GITHUB_ENV"
      with:
        fetch-depth: 0
    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@main
      with:
        extra_args: --only-verified